# Generated by Django 3.1.2 on 2022-01-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('auteur', models.CharField(max_length=60)),
                ('description', models.CharField(default='', max_length=500)),
                ('images', models.ImageField(default='images.png', upload_to='article_images')),
                ('contenu', models.CharField(max_length=10000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('professeur', models.CharField(max_length=60)),
                ('president', models.CharField(max_length=60)),
                ('horaire', models.CharField(default='', max_length=300)),
                ('description', models.CharField(default='', max_length=500)),
                ('avatar', models.ImageField(default='avatar.png', upload_to='avatars')),
                ('animation', models.ImageField(default='avatar.png', upload_to='avatars')),
                ('lien', models.CharField(max_length=1000)),
            ],
        ),
    ]
